### ISSUE TITLE
[Feature 5] Staff

### ISSUE THREAD

**Issue by zoeyzlee** [CSC207-2023Y-UofT/course-project-the-bbc#16]
Staff package handles types of employees, payment, and name, id, schedule, other info about workers 

Train Drivers (Zoey)
- Inspecting the vehicle and engine in preparation for a route
- Receiving and interpreting train orders
- Monitoring the speed, air pressure and other operational measurements of the train
- Maintaining contact with the conductor and informing them of changes to the train's condition

Admins (Grace)

**Comment by charlescheung22** [comment]
Done
